### ISSUE TITLE
Pre-release improvements

### ISSUE THREAD

**Issue by raymond-wells** [8x8Cloud/zerigodns#1]
We should do the following things before making this gem public:
- [x] Re-structure the files in the gem so there is 1 file per class. ( https://github.com/8x8Cloud/zerigo_dns/issues/2 )
- [x] Investigate an alternative to activeresource such as HTTPParty. ( https://github.com/8x8Cloud/zerigo_dns/issues/6 )
- [x] Add a wiki for documentation.  Document nuances, such as [the one discussed with `update_or_create`](https://github.com/8x8Cloud/zerigons/issues/418#issuecomment-62931019) ( https://github.com/8x8Cloud/zerigo_dns/issues/7 )
- [x] Zone & host template support.
- [x] ~ Investigate https://rubygems.org/gems/zerigo-designate as an alternative base for our gem. ~
- [x] Cover with lots of tests (unit & integration)
- [x] Change the name ( #8 )
